services:
  indexer:
    restart: always
    depends_on:
      - mongo
    networks:
      - mongo
      - ollama_network
    env_file:
      - .env.duck
    volumes:
      - ./services/discord-indexer:/app
      - ./shared:/app/shared
    build: ./services/discord-indexer

  twitch:
    restart: always
    depends_on:
      - mongo
    networks:
      - mongo
    env_file:
      - .env.twitch
    volumes:
      - ./services/twitch:/app
      - ./shared:/app/shared
    build: ./services/twitch

  dispatcher:
    restart: always
    depends_on:
      - mongo
    networks:
      - mongo
    env_file:
      - .env.duck
    volumes:
      - ./services/discord-dispatcher:/app
      - ./shared:/app/shared
    build: ./services/discord-dispatcher

  timmy:
    restart: always
    depends_on:
      - mongo
      - indexer
      - ollama
    networks:
      - mongo
      - ollama_network
    env_file:
      - .env.timmy
    volumes:
      - ./services/timmy:/app
      - ./shared:/app/shared
    build: ./services/timmy

  jim:
    restart: always
    depends_on:
      - mongo
      - indexer
      - ollama-gpu
    networks:
      - mongo
      - ollama_gpu_network
    env_file:
      - .env.jim
    volumes:
      - ./services/jim:/app
      - ./shared:/app/shared
    build: ./services/jim

  duckman:
    restart: always
    depends_on:
      - mongo
      - indexer
      - ollama
    networks:
      - mongo
      - ollama_network
    env_file:
      - .env.duck
    volumes:
      - ./services/Duckman:/app
      - ./shared:/app/shared
    build: ./services/Duckman
  duck:
    restart: always
    depends_on:
      - mongo
      - indexer
      - ollama
    ports:
      - 11435:11435
    networks:
      - mongo
      - ollama_network
    env_file:
      - .env.duck
    volumes:
      - ./services/duck:/app
      - ./shared:/app/shared
    build: ./services/duck

  zen:
    restart: always
    depends_on:
      - mongo
      - ollama
    networks:
      - mongo
      - ollama_network
    env_file:
      - .env.zen
    volumes:
      - ./services/zen:/app
      - ./shared:/app/shared
    build: ./services/zen

  generator:
    restart: always
    depends_on:
      - mongo
    networks:
      - mongo
    env_file:
      - .env.duck
    volumes:
      - ./services/generator:/app
      - ./shared:/app/shared
      - ./models:/app/models
    build: ./services/generator
    deploy:
      resources:
        reservations:
           devices:
            - driver: nvidia
              device_ids: [ "0" ]
              capabilities: [gpu]
  trainer:
    restart: always
    depends_on:
      - mongo
    networks:
      - mongo
    env_file:
      - .env.duck
    volumes:
      - ./services/trainer:/app
      - ./shared:/app/shared
      - ./models:/app/models
    build: ./services/trainer
    deploy:
      resources:
        reservations:
           devices:
            - driver: nvidia
              device_ids: [ "0" ]
              capabilities: [gpu]
  mongo:
    restart: always
    image: mongo
    volumes:
      - ./data/mongodb:/data/db
    networks:
      - mongo
    expose:
      - 27017
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command:
      redis-server --save 20 1 \
        --loglevel warning \
        --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data
  ollama:
    volumes:
      - ollama:/root/.ollama
    ports:
      - 11434:11434
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:latest
    environment:
      - OLLAMA_NUM_PARALLEL=10
    networks:
      - ollama_network


  ollama-gpu:
    # Uncomment below for GPU support
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu
    volumes:
      - ollama-gpu:/root/.ollama
    # Uncomment below to expose Ollama API outside the container stack
    # ports:
    #   - 11434:11434
    container_name: ollama-gpu
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:latest
    environment:
      - OLLAMA_NUM_PARALLEL=10
    networks:
      - ollama_gpu_network
volumes:
  ollama: {}
  ollama-gpu: {}
  cache:
    driver: local
networks:
  mongo:
  chroma:
  ollama_network:
  ollama_gpu_network: