services:
  indexer:
    restart: always
    depends_on:
      - mongo
    networks:
      - mongo
      - ollama_network
    env_file:
      - .env.duck
    volumes:
      - ./services/discord-indexer:/app
      - ./shared:/app/shared
    build: ./services/discord-indexer

  dispatcher:
    restart: always
    depends_on:
      - mongo
    networks:
      - mongo
    env_file:
      - .env.duck
    volumes:
      - ./services/discord-dispatcher:/app
      - ./shared:/app/shared
    build: ./services/discord-dispatcher

  timmy:
    restart: always
    depends_on:
      - mongo
      - ollama
    networks:
      - mongo
      - ollama_network
    env_file:
      - .env.timmy
    volumes:
      - ./services/timmy:/app
      - ./shared:/app/shared
    build: ./services/timmy

  generator:
    restart: always
    depends_on:
      - mongo
    networks:
      - mongo
    env_file:
      - .env.duck
    volumes:
      - ./services/generator:/app
      - ./shared:/app/shared
      - ./models:/app/models
    build: ./services/generator
    deploy:
      resources:
        reservations:
           devices:
            - driver: nvidia
              device_ids: [ "0" ]
              capabilities: [gpu]
  trainer:
    restart: always
    depends_on:
      - mongo
    networks:
      - mongo
    env_file:
      - .env.duck
    volumes:
      - ./services/trainer:/app
      - ./shared:/app/shared
      - ./models:/app/models
    build: ./services/trainer
    deploy:
      resources:
        reservations:
           devices:
            - driver: nvidia
              device_ids: [ "0" ]
              capabilities: [gpu]
  mongo:
    restart: always
    image: mongo
    volumes:
      - ./data/mongodb:/data/db
    networks:
      - mongo
    expose:
      - 27017
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command:
      redis-server --save 20 1 \
        --loglevel warning \
        --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data
  ollama:
    # Uncomment below for GPU support
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities:
    #             - gpu
    volumes:
      - ollama:/root/.ollama
    # Uncomment below to expose Ollama API outside the container stack
    ports:
      - 11434:11434
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:latest
    networks:
      - ollama_network

  # ollama-webui:
  #   build:
  #     context: ./ollama-webui
  #     args:
  #       OLLAMA_API_BASE_URL: '/ollama/api'
  #     dockerfile: Dockerfile
  #   image: ollama-webui:latest
  #   container_name: ollama-webui
  #   depends_on:
  #     - ollama
  #   ports:
  #     - 3000:8080
  #   environment:
  #     - "OLLAMA_API_BASE_URL=http://ollama:11434/api"
  #   extra_hosts:
  #     - host.docker.internal:host-gateway
  #   restart: unless-stopped

volumes:
  ollama: {}
  cache:
    driver: local
networks:
  mongo:
  chroma:
  ollama_network:
    driver: bridge