"""
Sends out approved messages generated by the duck gpt model to discord
client.
"""
import discord

from shared.discord import get_unsent_messages, send_message
import shared.settings as settings

import asyncio
intents = discord.Intents.default()
intents.message_content = True
# send messages intent
client = discord.Client(intents=intents)

@client.event
async def on_ready():
    print(f'Logged in as {client.user}')
    sent_messages=set()
    while True:
        try:
            unsent_messages = list(get_unsent_messages().limit(100))
            if unsent_messages:
                print("unsent messages found!", len(unsent_messages))
                for message in unsent_messages:
                    await asyncio.sleep(1)
                    await send_message(message,sent_messages,client)
            await asyncio.sleep(1)
        except Exception as e:
            print("somthing went wrong in dispatch!")
            print(e)



client.run(settings.DISCORD_TOKEN)
